#!/usr/bin/env python3

import re
import sys
import sqlite3

# Regex lifted from https://github.com/ashafer01/Nextrastout
patterns = [re.compile(r'\b([!-&*-~]+?)(\+\+|--)(?![!-~])'),
            re.compile(r'\(([ -~]+?)\)(\+\+|--)(?![!-~])')]

conn = sqlite3.connect("var/irsh.sqlite3")
c = conn.cursor()

c.execute('''
    CREATE TABLE IF NOT EXISTS karma (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        term TEXT UNIQUE,
        incs INT DEFAULT 0,
        decs INT DEFAULT 0
    )''')

for p in patterns:
    for m in re.finditer(p, ' '.join(sys.argv[1:])):
        if (m.group(2) == "++"):
            c.execute('''
                INSERT INTO karma(term, incs) VALUES(?, 1)
                ON CONFLICT(term) DO UPDATE SET incs=incs+1''', (m.group(1),))
        else:
            c.execute('''
                INSERT INTO karma(term, decs) VALUES(?, 1)
                ON CONFLICT(term) DO UPDATE SET decs=decs+1''', (m.group(1),))

conn.commit()
